### ISSUE TITLE
Nez Reference Rework

### ISSUE THREAD

**Issue by AngeredZeus** [SpencasaurusRex/ARA2D#4]
On first pull, currently Nez is set to 
`<ProjectReference Include="..\Nez\Nez.Portable\Nez.csproj">
      <Project>{8b90e065-141f-42e6-bc9c-f9a16e40adee}</Project>
      <Name>Nez</Name>
    </ProjectReference>
`
Which is presumably @SpencasaurusRex 's local install location. 
I believe whenever we pull/fetch this is breaking our references. I feel like there is a better way to do this.

**Comment by SyndaKitty** [comment]
Unfortunately I do not believe that there is a better way to do this.
The reference to Nez is a relative file path made so that the Nez and ARA2D folders have to be in the same folder. If you don't have Nez setup like this, anytime you pull down this file it will break for you.

Normally for locally different things like this, we would add the file to a the `.gitignore` to prevent it from being added to the repo, however the `.csproj` file defines what files to include in our project, so it's not something that we can exclude.

The fix, I think is just to make sure your Nez project is in the same folder as your ARA2D project.

**Comment by SyndaKitty** [comment]
Perhaps a better way to handle external libraries would be to have a `libs` folder under `ARA2D` that would hold all the external libraries we end up using. When a contributor forks this repo, all external libraries would be cloned under this folder. The `.gitignore` should amended to ignore folders in this directory.

Another thing worth looking into is GitHub submodules. We could potentially setup Nez as a child repository of ours.
